language: go

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -cover -race -coverprofile coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-ci
